### Default Konfig-Datei mit allen Einstellungen um das BITS-Training mit einem Webserver zu betreiben
baseURL = "/"
relativeURLs = false
uglyurls = false
disableSearch = false

languageCode = "de-DE"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir= false

metaDataFormat = "yaml"

title = "BITS | Behörden-IT-Sicherheitstraining"
theme = "hugo-theme-learn"

[params]
  description = "BITS, das kostenlose Behörden-IT-Sicherheitstraining, wurde vom Arbeitskreis Informationstechnologie des Städte- und Gemeindebundes NRW als webbasierter Lernkurs für die Beschäftigten in Behörden und anderen Einrichtungen erstellt. Es dient der Information und Sensibilisierung der Kolleginnen und Kollegen an IT-Arbeitsplätzen hinsichtlich der relevanten Sicherheitsthemen."
  author = "Dr. Lutz Gollan"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = true
  disableLandingPageButton = true
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  # Hier wird die für BITS angepasste blaue Variante eingestellt
  themeVariant = "bits"

  BITS = "BITS"
  Ver = "6.0.0"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]

[Languages.de]
title = "BITS | Behörden-IT-Sicherheitstraining"
weight = 1
languageName = "Deutsch"
landingPageURL = "/010-start/"
landingPageName = "<i class='fas fa-home'></i> Start"
Einrichtung = "Behörde oder Einrichtung"
Einrichtungen = "Behörden und Einrichtungen"

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> Weitere Informationen"
identifier = "wi"
url = "/300 infos/weitere-informationen/"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Herausgeber und Lizenz"
url = "/300 infos/herausgeber-und-lizenz/"
weight = 20

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Barrierefreiheit"
identifier = "usability"
url = "/300 infos/barrierefreiheit/"
weight = 30

[Languages.en]
title = "BITS | IT security training for public authorities"
weight = 2
languageName = "English"
landingPageURL = "/010-start/"
landingPageName = "<i class='fas fa-home'></i> Start"
Einrichtung = "Authority or institution"
Einrichtungen = "Authorities or institutions"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> more information"
identifier = "wi"
url = "/300 infos/weitere-informationen/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Publisher and License"
url = "/300 infos/herausgeber-und-lizenz/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Accessibility"
identifier = "usability"
url = "/300 infos/barrierefreiheit/"
weight = 30

[minify]
  # disabled because of issues with quiz module
  disableHTML = true