### Default Konfig-Datei mit allen Einstellungen um das BITS-Training mit einem Webserver zu betreiben
baseURL = "/"
canonifyURLs = true
relativeURLs = true
uglyurls = false

languageCode = "de-DE"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir= false

metaDataFormat = "yaml"

title = "BITS | Behörden-IT-Sicherheitstraining"
theme = "hugo-theme-relearn"

[params]
  description = "BITS, das kostenlose Behörden-IT-Sicherheitstraining, wurde vom Arbeitskreis Informationstechnologie des Städte- und Gemeindebundes NRW als webbasierter Lernkurs für die Beschäftigten in Behörden und anderen Einrichtungen erstellt. Es dient der Information und Sensibilisierung der Kolleginnen und Kollegen an IT-Arbeitsplätzen hinsichtlich der relevanten Sicherheitsthemen."
  author = "Dr. Lutz Gollan"
  showVisitedLinks = true
  disableSearch = false
  disableSearchHiddenPages = true
  disableSeoHiddenPages = true
  disableTagHiddenPages = true
  disableBreadcrumb = false
  disableToc = true
  disableNextPrev = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = true
  disableLandingPageButton = true
  titleSeparator = "::"
  themeVariant = [ "bits-normal", "bits-dark-mode", "bits-high-contrast"]

  # BITS unterstützt von Haus aus ein datenschutzfreundliches Tracking über GoatCounter oder alternativ Matomo.
  # Standardmäßig ist Tracking ausgeschaltet. Hier werden die Einstellungen für beide Dienste erläutert.
  # Benutzertracking über die Open Source-Anwendung GoatCounter
  # Online service via https://www.goatcounter.com/ oder self-hosted
  #
  #CODE für den Online Service, der bei Registrierung zum Tracking angegeben wurde (leer = deaktiviert, auch leer für self-hosted!)
  GoatCounter_ID = ""
  #
  # nur bei self-hosted die folgenden Werte setzen (sonst leer lassen!)
  # es ist möglich nur GountCounter_SRC zu setzten, wenn das count.js selbst gehostet wird.
  #URL des Endpoints wo das Script /count aufruft (bsp: "https://count.example.com", /count wird immer angehängt!)
  GoatCounter_URL = ""
  #Source für das Script Tag von dem count.js geladen wird (ohne http/https, mit Dateiname, bsp: "count.example.com/count.js", default = GoutCounter_URL, /count.js wird immer angehängt!)
  GoatCounter_SRC = ""

  # Benutzertracking über die Open Source-Anwendung Matomo
  # Online service via https://matomo.cloud/ oder self-hosted
  #
  #IDSITE der Webseite die in Matomo getrackt werden soll (leer = deaktiviert)
  Matomo_ID = ""
  #
  #URL von der das Tracking Script geladen wird (bsp: "example.matomo.cloud")
  Matomo_URL = ""
  #
  #für weitere Einstellungen/Anpassungen des Trackingscripts siehe -> "\BITS-hugo\layouts\partials\custom-header.html"
  #Das OptOut-Frame wird über den Shortcode {{< matomo >}} erzeugt. Optional kann ein CSS Style String übergeben werden {{< matomo "border: 2px solid black; height: 170px; width: 100%; background: #fff" >}}

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]

[Languages.de]
title = "BITS | Behörden-IT-Sicherheitstraining"
weight = 1
languageName = "Deutsch"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Start"

BITS = "BITS"
BITS_Titel = "Behörden-IT-Sicherheitstraining"
Ver = "6.2.0-beta1"
Release = "aus Herbst 2022"
BITS_Password_Length = "acht"
Einrichtung = "Behörde oder Einrichtung"
Einrichtungen = "Behörden und Einrichtungen"

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> Weitere Informationen"
identifier = "wi"
url = "/weitere-informationen/"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Herausgeber und Lizenz"
url = "/herausgeber-und-lizenz/"
weight = 20

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Barrierefreiheit"
identifier = "usability"
url = "/barrierefreiheit/"
weight = 30

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract'></i> Impressum"
identifier = "imprint"
url = "/impressum/"
weight = 40

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-user-shield'></i> Datenschutz"
identifier = "datasecurity"
url = "/datenschutz/"
weight = 50

[Languages.en]
title = "BITS | IT security training for public authorities"
description = "BITS, the free IT security training for public authorities, was created by the Information Technology Working Group of the Association of Towns and Municipalities in North Rhine-Westphalia as a web-based learning course for employees in public authorities and other institutions. It serves to inform and sensitize colleagues at IT workstations with regard to relevant security topics."
weight = 2
languageName = "English"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Start"

BITS = "BITS"
BITS_Titel = "Authority-IT-Security Training"
Ver = "6.2.0-beta1"
Release = "from autum 2022"
BITS_Password_Length = "eight"
Einrichtung = "Authority or institution"
Einrichtungen = "Authorities or institutions"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> more information"
identifier = "wi"
url = "/weitere-informationen/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Publisher and License"
url = "/herausgeber-und-lizenz/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Accessibility"
identifier = "usability"
url = "/barrierefreiheit/"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract'></i> Imprint"
identifier = "imprint"
url = "/impressum/"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-user-shield'></i> Datasecurity"
identifier = "datasecurity"
url = "/datenschutz/"
weight = 50

[minify]
  # disabled because of issues with quiz module
  disableHTML = true
