### Default Konfig-Datei mit allen Einstellungen um das BITS-Training mit einem Webserver zu betreiben
baseURL = "/"
canonifyURLs = true
relativeURLs = true
uglyurls = false

languageCode = "de-DE"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir= false

metaDataFormat = "yaml"

title = "BITS | Behörden-IT-Sicherheitstraining"
theme = "hugo-theme-relearn"

[params]
  description = "BITS, das kostenlose Behörden-IT-Sicherheitstraining, wurde vom Arbeitskreis Informationstechnologie des Städte- und Gemeindebundes NRW als webbasierter Lernkurs für die Beschäftigten in Behörden und anderen Einrichtungen erstellt. Es dient der Information und Sensibilisierung der Kolleginnen und Kollegen an IT-Arbeitsplätzen hinsichtlich der relevanten Sicherheitsthemen."
  author = "Dr. Lutz Gollan"
  showVisitedLinks = true
  disableSearch = false
  disableBreadcrumb = false
  disableToc = true
  disableNextPrev = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = true
  disableLandingPageButton = true
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  # Hier wird die für BITS angepasste blaue Variante eingestellt
  themeVariant = "bits"

  BITS = "BITS"
  BITS_Titel = "Behörden-IT-Sicherheitstraining"
  Ver = "6.1"
  Release = "aus Frühjar 2022"
  BITS_Password_Length = "8"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]

[Languages.de]
title = "BITS | Behörden-IT-Sicherheitstraining"
weight = 1
languageName = "Deutsch"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Start"
Einrichtung = "Behörde oder Einrichtung"
Einrichtungen = "Behörden und Einrichtungen"

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> Weitere Informationen"
identifier = "wi"
url = "/weitere-informationen/"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Herausgeber und Lizenz"
url = "/herausgeber-und-lizenz/"
weight = 20

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Barrierefreiheit"
identifier = "usability"
url = "/barrierefreiheit/"
weight = 30

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract'></i> Impressum"
identifier = "imprint"
url = "/impressum/"
weight = 40

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-user-shield'></i> Datenschutz"
identifier = "datasecurity"
url = "/datenschutz/"
weight = 50

[Languages.en]
title = "BITS | IT security training for public authorities"
weight = 2
languageName = "English"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Start"
Einrichtung = "Authority or institution"
Einrichtungen = "Authorities or institutions"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> more information"
identifier = "wi"
url = "/weitere-informationen/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Publisher and License"
url = "/herausgeber-und-lizenz/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Accessibility"
identifier = "usability"
url = "/barrierefreiheit/"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract'></i> Imprint"
identifier = "imprint"
url = "/impressum/"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-user-shield'></i> Datasecurity"
identifier = "datasecurity"
url = "/datenschutz/"
weight = 50

[minify]
  # disabled because of issues with quiz module
  disableHTML = true
