### Default Konfig-Datei mit allen Einstellungen um das BITS-Training mit einem Webserver zu betreiben
baseURL = "/"
relativeURLs = false
uglyurls = false
disableSearch = false

languageCode = "de-DE"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir= false

metaDataFormat = "yaml"

title = "BITS | Behörden-IT-Sicherheitstraining"
theme = "hugo-theme-learn"

[params]
  description = "BITS, das kostenlose Behörden-IT-Sicherheitstraining, wurde vom Arbeitskreis Informationstechnologie des Städte- und Gemeindebundes NRW als webbasierter Lernkurs für die Beschäftigten in Behörden und anderen Einrichtungen erstellt. Es dient der Information und Sensibilisierung der Kolleginnen und Kollegen an IT-Arbeitsplätzen hinsichtlich der relevanten Sicherheitsthemen."
  author = "Dr. Lutz Gollan"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableAssetsBusting = true
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  # Hier wird die für BITS angepasste blaue Variante eingestellt
  themeVariant = "bits"
  
  BITS = "BITS"
  Ver = "6.0beta3"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages.de]
title = "BITS | Behörden-IT-Sicherheitstraining"
weight = 1
languageName = "Deutsch"
Einrichtung = "Behörde oder Einrichtung"
Einrichtungen = "Behörden und Einrichtungen"

[[Languages.de.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30

[Languages]
[Languages.en]
title = "BITS | IT security training for public authorities"
weight = 1
languageName = "English"
Einrichtung = "Authority or institution"
Einrichtungen = "Authorities or institutions"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[minify]
  # disabled because of issues with quiz module
  disableHTML = true