### Diese Datei enhält alle abweichenden Einstellungen um das Tranining ohne einen Web-Server zu betreiben
###
### Generiert wird die Version mit dem Befehl:
### hugo --environment html --cleanDestinationDir
relativeURLs = true
uglyurls = true

[params]
  ### Die Suche funktioniert nur beim Betrieb über einen Web-Server!!
  ##disableSearch = true <- soll jetzt auch über file-urls laufen!
  disableBreadcrumb = true
  disableExplicitIndexURLs = false

[Languages]

[Languages.de]
landingPageURL = "/index.html"

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> Weitere Informationen"
identifier = "wi"
url = "/mehr/weitere-informationen.html"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Herausgeber und Lizenz"
url = "/mehr/herausgeber-und-lizenz.html"
weight = 20

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Barrierefreiheit"
identifier = "usability"
url = "/mehr/barrierefreiheit.html"
weight = 30

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract'></i> Impressum"
identifier = "imprint"
url = "/mehr/impressum.html"
weight = 40

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-fw fa-user-shield'></i> Datenschutz"
identifier = "datasecurity"
url = "/mehr/datenschutz.html"
weight = 50

[Languages.en]
landingPageURL = "/index.html"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> more information"
identifier = "wi"
url = "/mehr/weitere-informationen.html"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-id-card'></i> Publisher and License"
url = "/mehr/herausgeber-und-lizenz.html"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wheelchair'></i> Accessibility"
identifier = "usability"
url = "/mehr/barrierefreiheit.html"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract'></i> Imprint"
identifier = "imprint"
url = "/mehr/impressum.html"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-user-shield'></i> Datasecurity"
identifier = "datasecurity"
url = "/mehr/datenschutz.html"
weight = 50
