### Konfig-Datei für Entwicklungsumgebung
baseURL = "https://bits-training.github.io/training/"

[Languages]

[Languages.de]
title = "TEST BITS | Behörden-IT-Sicherheitstraining"

BITS = "TEST BITS"
BITS_Titel = "Behörden-IT-Sicherheitstraining"
Ver = "6.x.x-dev"
Release = "bleeding edge testing"

[Languages.en]
title = "TEST BITS | IT security training for public authorities"

BITS = "TEST BITS"
BITS_Titel = "Authority-IT-Security Training"
Ver = "6.x.x-dev"
Release = "bleeding edge testing"
